### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by apicht** [cptactionhank/docker-atlassian-confluence#11]
The documentation link (cptactionhank.github.io/docker-atlassian-confluence) returns a 404 error.

**Comment by cptactionhank** [comment]
Hi, thanks for reporting this.

I hoped I'd get around to create some helpful documentation this weekend, but alas didn't happen. Sorry about this and I will make this a priority for when I have some free time, meanwhile you can use http://cptactionhank.github.io/docker-atlassian-jira/ as inspiration.

**Comment by cptactionhank** [comment]
The website is up and running
