### ISSUE TITLE
Mysql connector in wrong folder?

### ISSUE THREAD

**Issue by GogLlundain** [cptactionhank/docker-atlassian-confluence#12]
The mysql connector didn't work for me. I copied it onto my host and used `-v` to put it in /opt/atlassian/confluence/confluence/WEB-INF/lib on the container. Seemed to unblock my issue.

**Comment by cptactionhank** [comment]
Can you elaborate on which version/tag you are using, the latest versions includes acceptance tests using the embedded, Postgres, and MySQL databases.

Kind regards,

Martin Jensen

**Comment by GogLlundain** [comment]
Hi Martin,
I was using the 5.8.5 originally and then I tried the latest too. I was getting error message like 'Spring application Context has not been set' on both tags. I remembered seeing this message when I was installing confluence manually and I hadn't copied the mysql jar file to the lib folder. I had a google and [this article](https://confluence.atlassian.com/x/p6kCDQ) turned up. So I added this to my ``docker run`` comand:

-v /localfolder/mysql-connector-java-5.1.36-bin.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-5.1.36-bin.jar

It works with this, it doesn't without it.

FYI I'm running a mysql container that's linked to my confluence container. Interestingly your Jira container worked fine, it's linked to this same mysql container.

**Comment by cptactionhank** [comment]
I'll look into this and see if I can reproduce the same problem you are experiencing. Thank you for the more detailed description, I will see what I can figure out.

Kind regards,

Martin Jensen

**Comment by GogLlundain** [comment]
Thanks Martin, I appreciate what you're doing :+1:

**Comment by cptactionhank** [comment]
Hi Gareth, I have looked in to the issue and I believe you are right (I’m getting same problems). I will need to update and streamline the acceptance tests and include mysql databases as well to jira and jira-software.

With some luck I’ll get to implementing this on sunday, though due to a scheduling conflict with a hangover this might first be fixed at a little later time. Thank you for reporting about the troubles about MySQL.

> On 28 Oct 2015, at 11:21, Gareth Jones <notifications@github.com> wrote:
> 
> Thanks Martin, I appreciate what you're doing 
> 
> —
> Reply to this email directly or view it on GitHub.
> 


--
Kind regards,

Martin Jensen
