### ISSUE TITLE
Proxy Support in Server.xml

### ISSUE THREAD

**Issue by blacklabelops** [cptactionhank/docker-atlassian-confluence#15]
I need to set proxyName and proxyPort at container startup inside server.xml. I have my confluence running behind nginx.

Suggestion: Add the following Environment Variables and they should modify the proxy entries inside the server.xml:

* CONFLUENCE_PROXY_NAME -> Sets attribute proxyName 
* CONFLUENCE_PROXY_PORT -> Sets attribute proxyPort
 
XPATH:

* //Connector/@proxyName
* //Connector/@proxyPort

I would like to create a pull request but there is already one pending that introduces already introduces a docker-entrypoint.

**Comment by cptactionhank** [comment]
I haven't heard back from him since i wrote some comments, so i'll schedule to do something about thus as soon as i have time.

**Comment by blacklabelops** [comment]
Finished with my features. Can be found here https://github.com/blacklabelops/confluence. You can take these when you have time, the rewrapper already works fine for me!

**Comment by cptactionhank** [comment]
Just to follow up, this is coming, as of now all the JIRA applications has been updated and next up will be Confluence.

**Comment by t5unamie** [comment]
Could the same features not have been added by simply doing the things done Jira?

https://github.com/cptactionhank/docker-atlassian-jira/blob/master/docker-entrypoint.sh

I am personally looking to set the context path as well.
