### ISSUE TITLE
apt-get update on this container?

### ISSUE THREAD

**Issue by msimonc** [cptactionhank/docker-atlassian-confluence#21]
? Is there a problem / Is it a good idea to periodically:

docker exec -it -u root atlassn-conflnce bash

apt-get update 

Thanks!

**Comment by cptactionhank** [comment]
I think it's better to periodically check if the image has been updated and then create a new container using that image with the volumes from the old one. This way you would get the latest update and JRE version, since the image bases itself on the official java image, when that gets updated.

**Comment by cptactionhank** [comment]
Closed due to inactivity
