### ISSUE TITLE
5.9.12 not found in repository docker.io/cptactionhank/atlassian-confluence

### ISSUE THREAD

**Issue by phlegx** [cptactionhank/docker-atlassian-confluence#23]
Hi!

Getting the following error when trying to use the newest  5.9.12 tag: 

```ERROR: Service 'confluence' failed to build: Tag 5.9.12 not found in repository docker.io/cptactionhank/atlassian-confluence```

thanks!

**Comment by cptactionhank** [comment]
It will be available later today, CET timezone

Kind regards,

Martin Jensen

**Comment by cptactionhank** [comment]
Tag 5.9.12 is now available. It seems there's a problem with the Docker Hub and my automated builds.
