### ISSUE TITLE
Volumes Don't Respect ENV Variables

### ISSUE THREAD

**Issue by sebkouba** [cptactionhank/docker-atlassian-confluence#27]
First of all thanks for providing the images. I've found them very useful! And I have a question:
In der Dockerfile line 52, shouldn't 
`VOLUME ["/var/atlassian/confluence", "/opt/atlassian/confluence/logs"]` 
instead be 
`VOLUME ["${CONF_HOME}", "${CONF_INSTALL}/logs"]`
Otherwise the volumes may end up in the wrong place... Or did I misunderstand something?

**Comment by cptactionhank** [comment]
You are certainly right, that would be the best way to do it, but earlier at the time I started working on these images it couldn't be written this way and admittedly I haven't tested it in the newer versions of Docker. The same should apply to `WORKDIR` and `CMD` perhaps I will try this out again at a later point when I have time but in the meantime PR's are welcome if it works :)

**Comment by cptactionhank** [comment]
Please be aware that you cannot really change the install path nor the home path inside the running container by overriding the environment variable when starting the container. Rather they should be seen as read-only variables useful for shortcuts and scripting purposes.

**Comment by sebkouba** [comment]
I've played around with this (on creation) and it seems that the variable expansion doesn't work as expected. The volumes don't get created.
Dockerfile with
`VOLUME ["${JIRA_HOME}", "${JIRA_INSTALL}/logs"]`
`WORKDIR "${JIRA_HOME}""`

does not work with setting the variable in docker run
`-e JIRA_HOME='/h_jira' -e JIRA_INSTALL='/i_jira'`

[https://github.com/docker/docker/issues/2637](https://github.com/docker/docker/issues/2637)

I guess this isn't as useful as I had thought but at the same time I find the behaviour surprising. Maybe I just missed something entirely but this isn't a big problem for me so feel free to close this issue.
