### ISSUE TITLE
Confluence v. 5.8.16 Docker image?

### ISSUE THREAD

**Issue by evgf** [cptactionhank/docker-atlassian-confluence#30]
Hello everyone, we are trying to upgrade to v.5.8.16 second week in a row but still see no such version in the repository although it is listed as available for quite some time:

```
docker pull cptactionhank/atlassian-confluence:5.8.16
Pulling repository docker.io/cptactionhank/atlassian-confluence
Tag 5.8.16 not found in repository docker.io/cptactionhank/atlassian-confluence

```
Any chance you can have a look at it?

**Comment by cptactionhank** [comment]
I can see there are GitHub branches for these, but no tags at docker hub. Earlier I have had problems with the autobuild feature on docker hub and it looks like I missed these. They will be built later today.

Thank you for this.

**Comment by cptactionhank** [comment]
Software versions and corresponding tags for 5.8.16, 5.8.17, and 5.8.18 are now available.

**Comment by evgf** [comment]
Perfect, see it :)
