### ISSUE TITLE
Some of the documentation content looks like automated spam.

### ISSUE THREAD

**Issue by abrookewood** [cptactionhank/docker-atlassian-confluence#31]
Hi Martin,

Just pointing out that some of the content looks auto-generated. Not sure if something has gone wrong or if it is just filler? For example, under the title "Memory property", the content is this:
"Gang receding fetishism smart-plastic Shibuya systemic carbon Legba DIY towards sentient. Into claymore mine weathered gang rain tanto man engine dead Chiba tower sub-orbital San Francisco table."

Anyway, nice job on the images - thanks.

**Comment by mccartney** [comment]
Where do you see that?

**Comment by abrookewood** [comment]
Here for example: https://cptactionhank.github.io/docker-atlassian-jira/
![2016-10-12 23_36_09-atlassian jira](https://cloud.githubusercontent.com/assets/12084172/19310203/b01a040c-90d4-11e6-8e9b-7c0332298553.png)

**Comment by mccartney** [comment]
OK. Then it's about docker-atlassian-jira and not docker-atlassian-confluence. That's why I didn't see it.

**Comment by cptactionhank** [comment]
Thank you for raising while it is indeed mumble text I have not have found the time to write proper content since it's the hardest part out of everything in these projects :-)
