### ISSUE TITLE
The image should allow for injecting a custom SSL certificate to java cacerts

### ISSUE THREAD

**Issue by mccartney** [cptactionhank/docker-atlassian-confluence#35]
The image should allow for injecting a custom SSL certificate to java cacerts.
That turned out to be needed when I had an internal Active Directory (AD) with a self-signed certificate. So the generic world-wide ones wouldn't be enough.

More information in Atlassian documentation:
https://confluence.atlassian.com/doc/configuring-an-ssl-connection-to-active-directory-229838458.html
which is a bit misleading, as it advertises a Confluence add-on/plugin which does that, which seems to be out-of-date information as the plugin is not compatible any more (https://marketplace.atlassian.com/plugins/com.atlassian.confluence.plugins.ssl/server/overview)

**Comment by mccartney** [comment]
I suggested a code change which worked for us in 5.10.8 - thus, I submitted the pull-request #34.

If it gets accepted - I am happy to provide some documentation on how to use it, but I am not sure where to put it.

**Comment by cptactionhank** [comment]
Thank you for this, I'll review this as soon as possible

**Comment by cptactionhank** [comment]
Accepted. I would appreciate some kind of README section on how to use this
