### ISSUE TITLE
container is not running 

### ISSUE THREAD

**Issue by starjason** [cptactionhank/docker-atlassian-confluence#65]
docker run --detach --publish 8090:8090 cptactionhank/atlassian-confluence:latest
e6c3dd9337e2e96e9abd219f17f7586b0556251fd3cadc450d4945037ca4086c

CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                     PORTS               NAMES
e6c3dd9337e2        cptactionhank/atlassian-confluence:latest   "/docker-entrypoin..."   15 seconds ago      Exited (1) 8 seconds ago                       adoring_nightingale

**Comment by cptactionhank** [comment]
Bummer. You should look more into why, checking stdout and stderr for more information.
