### ISSUE TITLE
Java Open JDK Problem

### ISSUE THREAD

**Issue by dawidek88** [cptactionhank/docker-atlassian-confluence#75]
Hello cptactionhank.

Can you please adjust the confluence image with the compatible Java version (see https://confluence.atlassian.com/confkb/update-the-confluence-docker-image-to-use-oracle-jdk-829062521.html). I would be very happy.

The application always says that the Java version does not fit.

**Comment by Hilzerak** [comment]
Would be very nice, Yes! UP

**Comment by DanKrue80** [comment]
Same issue here running 6.11. Would be great if you'd fix this.
btw, great work Captain :)

**Comment by aney1** [comment]
Use of oracle jdk wasn't an option because of licensing.
But now Atlassian announced support of OpenJDK!
Are you considering changing your Java Runtime to the officialy supported one by adoptopenjdk?
There are Docker Images available here: https://hub.docker.com/r/adoptopenjdk/openjdk8
