### ISSUE TITLE
Local data should be in /var/lib/atlassian/confluence by default per Linux filesystem conventions

### ISSUE THREAD

**Issue by frederickding** [cptactionhank/docker-atlassian-confluence#9]
This is a semantic suggestion about the default path for local data. While it is customizable for an admin by changing the environmental variables in the Dockerfile and rebuilding such an image, the default settings are in a not-quite-sensical place: `/var/local`.

The [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) suggests that application state (e.g. databases, etc) are stored in `/var/lib`. Major databases and applications all follow this convention. I believe Atlassian products by default also suggest that location.

I'll admit that, in a Docker image, the exact path to data doesn't matter much (hence frequently images use non-standard locations like `/www` and `/data`) since they can be stored in data volumes or mounted to a location on the Docker host.

Unfortunately, migrating might be a pain for legacy users... so perhaps it's better off not changing this since the gains are so miniscule for the risks...

**Comment by cptactionhank** [comment]
Thank you for getting back on this, it is truly something I should be thinking more about and maybe streamline for the other Docker images as well. Sorry for being so long about responding, vacation and all.

From https://confluence.atlassian.com/display/JIRA/JIRA+Home+Directory we get the recommended data directory to be ```/var/atlassian/application-data/jira```

Where I personally like my choice better versus `/var/atlassian`, but I see your point and do think it makes better sense.


Now when we are on the FHS subject, what do you think about the installation directory? I think it kinda makes sense, however the Atlasssian installer uses ```/opt/atlassian```.

**Comment by frederickding** [comment]
Hey, thanks for being responsive and offering your response.

It's my understanding that, in general, there are two good, semantic places into which to install software from sources other than distro packages: `/usr/local` and `/opt`. However, the general expectation is that `/usr/local` functions like `/usr` -- with immediate subdirectories like `bin`. `/usr/local/bin` is often on the PATH. It's designed to be easy to use when, for instance, an end-user installs a different version of Ruby or Python from what the OS offers. The creation of new directories underneath, to isolate a particular vendor package without adding executables to a PATH-included location, is exactly the sort of thing that is semantically suited to being in `/opt/atlassian/<whatever>`.

Of course, it's *all* semantics. And in a Dockerized container, it doesn't really make much of a difference, except when a user is manually conducting maintenance from the shell.

**Comment by cptactionhank** [comment]
Good point, since it will influence new work I do, it would be good to know best practice and the more "right" places to put things. 

However I must confess I do find it weird from the documentation that the sub-directory naming requirements, requires either a name or a LANANA registered name, as it still makes the choosing of a name very loosely defined.

```
Directory	Description
<package>	Static package objects
<provider>	LANANA registered provider name
```

Or maybe that's a whole other thing.

**Comment by cptactionhank** [comment]
The now on the installation directory will be located at `/opt/atlassian/confluence` and home directory will be `/var/atlassian/confluence`, I think this should make sense.
